version: "3"
services:
  visionpython:
    build: .
    container_name: object-tracker-python
    image: aidoop/object-tracker-python:latest
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
      #- ./logs:/app/logs
    environment:
      - DISPLAY=unix$DISPLAY
    stdin_open: true
